on:
  push:
    branches:
      - main

name: Deploy website on push

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy file
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: u271805410.fox2dev.com
          server: 154.56.33.57
          port: 22
          local_path: "./*"
          remote_path: "/public_html/"
          sftp_only: true
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
