name: Deploy website on push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code source
        uses: actions/checkout@v2

      - name: Exécuter une commande
        run: echo "Hello, World!"
